data_dir = "/var/lib/vector"

[sources.from_vector]
type = "vector"
version = "2"
address = "0.0.0.0:8686"
tls.enabled = true
tls.ca_file = "/etc/vector/ca.pem"
tls.crt_file = "/etc/vector/cert.pem"
tls.key_file = "/etc/vector/key.pem"
tls.verify_certificate = true

[sinks.console]
type = "console"
inputs = [ "from_vector" ]
target = "stdout"
  [sinks.console.encoding]
  codec = "json"
